%% Straight Line
function [position,orientation,velocity,acceleration,angularVelocity, referenceLocation] = ...
    generateTrajectory(trajectoryFS)    
    duration = 100;
    enu1 = [0,0,0]; enu2 = [1732.1,1732.1,0];
    trajectory = waypointTrajectory( ...
        'Waypoints', [enu1;enu2], ...
        'TimeOfArrival',[0;duration], ...
        'SamplesPerFrame',duration*trajectoryFS - 1, ...
        'SampleRate',trajectoryFS, ...
        'AutoPitch', false, ...
        'AutoBank', false, ...
        'ReferenceFrame', 'ENU');
    [position,orientation,velocity,acceleration,angularVelocity] = ...
        trajectory();
    referenceLocation = [-33.861661, 151.209443, 0];
end

%% Circle
% function [position,orientation,velocity,acceleration,angularVelocity, referenceLocation] = ...
%     generateTrajectory(trajectoryFS)    
%     duration = 100;
%     enu1 = [0,0,0];
%     enu2 = [2000,2000,0];
%     trajectory = waypointTrajectory( ...
%         'Waypoints', [enu1;enu2;enu1], ...
%         'TimeOfArrival',[0;duration/2; duration], ...
%         'SamplesPerFrame',duration*trajectoryFS - 1, ...
%         'SampleRate',trajectoryFS, ...
%         'AutoPitch', false, ...
%         'AutoBank', false, ...
%         'ReferenceFrame', 'ENU');
%     [position,orientation,velocity,acceleration,angularVelocity] = ...
%         trajectory();
%     referenceLocation = [-33.861661, 151.209443, 0];
% end

%% Zig-Zag
% function [position,orientation,velocity,acceleration,angularVelocity, referenceLocation] = ...
%     generateTrajectory(trajectoryFS)    
%     duration = 100;
%     enu1 = [0,0,0];
%     enu2 = [300,300,0];
%     enu3 = [0,600,0];
%     enu4 = [300,900,0];
%     trajectory = waypointTrajectory( ...
%         'Waypoints', [enu1;enu2;enu3;enu4], ...
%         'TimeOfArrival',[0;duration/3;duration*2/3;duration], ...
%         'SamplesPerFrame',duration*trajectoryFS - 1, ...
%         'SampleRate',trajectoryFS, ...
%         'AutoPitch', false, ...
%         'AutoBank', false, ...
%         'ReferenceFrame', 'ENU');
%     [position,orientation,velocity,acceleration,angularVelocity] = ...
%         trajectory();
%     referenceLocation = [-33.861661, 151.209443, 0];
% end

%% Stationary
% function [position,orientation,velocity,acceleration,angularVelocity, referenceLocation] = ...
%     generateTrajectory(trajectoryFS)    
%     duration = 100;
%     enu1 = [0,0,0];
%     trajectory = waypointTrajectory( ...
%         'Waypoints', [enu1;enu1], ...
%         'TimeOfArrival',[0;duration], ...
%         'SamplesPerFrame',duration*trajectoryFS - 1, ...
%         'SampleRate',trajectoryFS, ...
%         'AutoPitch', false, ...
%         'AutoBank', false, ...
%         'ReferenceFrame', 'ENU');
%     [position,orientation,velocity,acceleration,angularVelocity] = ...
%         trajectory();
%     referenceLocation = [-33.861661, 151.209443, 0];
% end