%% gpsModel.m
% Produces simulated gps data given a certain trajectory described by 8.3.1
% in the report.
function [GPSPositionLLA, GPSVelocityLLA] = ...
    gpsModel(gpsFS, trajectoryFS, position, velocity, referenceLocation)
    GPS = gpsSensor( ...
        'HorizontalPositionAccuracy',10, ...
        'VerticalPositionAccuracy',10, ...
        'VelocityAccuracy',10, ...
        'DecayFactor',0.25, ...
        'SampleRate',gpsFS, ...
        'ReferenceLocation',referenceLocation, ...
        'ReferenceFrame', 'ENU');

    [GPSPositionLLA, GPSVelocityLLA] = ... 
        GPS(position(1:trajectoryFS/gpsFS:end,:), ...
        velocity(1:trajectoryFS/gpsFS:end,:));
end

